### PR TITLE
Orphaned volumes add to 'Projected Usage'

### PR DESCRIPTION
**Pull request by bodom0015**
Resolves issue #24

### CODE REVIEW

**Comment by bodom0015** [comment]
Test image available here under the tag *gh-issue-24*:
https://hub.docker.com/r/ndslabs/ndslabs-gui/tags/

**Comment by craig-willis** [comment]
I noticed that a new page is displayed in this build when the storage quota is set to 0 (contact an administrator to request increase). Is this intended?

**Comment by craig-willis** [comment]
Confirmed working in build gh-issue-24.

**Comment by bodom0015** [comment]
@craig-willis Yes, this is intentional. This is the page displayed when the user has reached their storage allocation quota. We do not handle the case where their initial quota is zero, since the "Create Account" function initializes this field to 10GB.

**Pull request merged**
